import React, { useMemo, useState } from "react";
import {
  House, Receipt, PaperPlaneTilt, Headset, UserCircle, Bell, ArrowLeft, Eye, EyeSlash,
  QrCode, Wallet, DotsThree, ShieldCheck, CheckCircle, Copy, ShareNetwork, MagnifyingGlass,
  SlidersHorizontal, ChatCircleDots, WarningCircle, Camera, FileText, LinkSimple, Phone,
  BookOpen, UsersThree, GearSix, Lock, Fingerprint, Key, DeviceMobile, Bank, Plus,
  SignOut, IdentificationCard, MapPin, CaretRight, Package
} from "@phosphor-icons/react";
import "./mobile.css";

const money = (n) => `GH₵ ${Number(n).toLocaleString("en-GH", {minimumFractionDigits:2, maximumFractionDigits:2})}`;
const sampleTx = [
  {id:"PP482910", item:"MacBook Air (Used)", amount:12500, status:"In Escrow", date:"14 Sep 2026", party:"Ama Serwaa"},
  {id:"PP482909", item:"iPhone 14 Pro", amount:8200, status:"Completed", date:"10 Sep 2026", party:"Kofi Mensah"},
  {id:"PP661028", item:"Nike Air Force 1", amount:1800, status:"Disputed", date:"08 Sep 2026", party:"Daniel K."},
  {id:"PP558774", item:"Sony WH-1000XM5", amount:2300, status:"Completed", date:"01 Sep 2026", party:"Kwame A."}
];

function Logo({small=false}){
  return <div className={`brand ${small?"small":""}`}>
    <svg className="brand-mark" viewBox="0 0 64 64" aria-hidden="true">
      <g fill="none" stroke="currentColor" strokeWidth="4.2" strokeLinecap="round">
        <path d="M9 39c0-17 9-28 23-28s23 9 23 22c0 12-8 21-19 21"/><path d="M14 44V35c0-13 7-21 18-21 11 0 18 7 18 18 0 9-6 16-14 16"/><path d="M20 49V34c0-8 5-14 12-14s12 5 12 12c0 7-5 11-10 11"/><path d="M26 52V34c0-4 2-7 6-7 4 0 6 3 6 6"/>
      </g><circle cx="34" cy="29" r="8.5" className="coin"/><text x="34" y="33" textAnchor="middle" fontSize="11" fontWeight="800" fill="#0a5c3e">₵</text>
    </svg><div><strong>Proof<span>Pay</span></strong><small>Pay Safe. Pay Smart.</small></div>
  </div>
}

function Shell({screen,setScreen,children,title,back=true,profile=true}){
  const nav=[["home",House,"Home"],["transactions",Receipt,"Transactions"],["send",PaperPlaneTilt,"Pay"],["support",Headset,"Support"],["profile",UserCircle,"Profile"]];
  return <div className="app-bg"><div className="phone-shell"><div className="statusbar"><b>9:41</b><span>● ● ●</span></div><div className="app-head">{back?<button className="icon-btn" onClick={()=>setScreen("home")}><ArrowLeft/></button>:<Logo small/>}<div className="head-title">{title}</div>{profile?<><button className="icon-btn"><Bell/></button><div className="avatar">EA</div></>:<span/>}</div><main className="screen-body">{children}</main><nav className="bottom-nav">{nav.map(([id,Icon,label])=><button key={id} className={screen===id?"active":""} onClick={()=>setScreen(id)}><Icon weight={id==="send"?"fill":"regular"}/><span>{label}</span></button>)}</nav></div></div>
}

function Auth({mode,setMode,onAuth}){
  const [show,setShow]=useState(false),[email,setEmail]=useState(""),[pw,setPw]=useState(""),[name,setName]=useState("");
  return <div className="auth-wrap"><div className="auth-card"><Logo/><div className="auth-hero"><Fingerprint weight="duotone"/><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>Secure payments. Smarter trade.</p></div><form onSubmit={e=>{e.preventDefault(); if(!email||!pw||(mode==="signup"&&!name)) return; localStorage.setItem("proofpay_demo_user",JSON.stringify({name:name||"Emmanuella Adu-Boahene",email})); onAuth();}}>{mode==="signup"&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" required/></label>}<label>Email or phone<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" required/></label><label>Password<div className="password"><input type={show?"text":"password"} value={pw} onChange={e=>setPw(e.target.value)} placeholder="••••••••" required minLength={6}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeSlash/>:<Eye/>}</button></div></label><button className="primary full" type="submit">{mode==="login"?"Log in":"Create account"}</button></form><p className="auth-switch">{mode==="login"?"New to ProofPay?":"Already have an account?"} <button onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Sign up":"Log in"}</button></p><div className="trust-row"><ShieldCheck/> Your demo data stays on this device.</div></div></div>
}

export function MobileApp(){
 const [authed,setAuthed]=useState(()=>!!localStorage.getItem("proofpay_demo_user")); const [authMode,setAuthMode]=useState("login"); const [screen,setScreen]=useState("home"); const [amount,setAmount]=useState(8000); const [recipient,setRecipient]=useState("Ama Serwaa"); const [selectedTx,setSelectedTx]=useState(sampleTx[0]); const [notifs,setNotifs]=useState(4); const user=useMemo(()=>JSON.parse(localStorage.getItem("proofpay_demo_user")||"{}"),[authed]);
 if(!authed) return <Auth mode={authMode} setMode={setAuthMode} onAuth={()=>setAuthed(true)}/>;
 const go=(s)=>setScreen(s);
 const views={
  home:<Shell screen={screen} setScreen={setScreen} back={false}><section className="home-greeting"><div><p>Good morning,</p><h1>{user.name?.split(" ")[0]||"Emmanuella"}</h1></div><button className="icon-btn" onClick={()=>{setNotifs(0);go("notifications")}}><Bell/><i>{notifs||""}</i></button></section><div className="hero-card"><div><small>Secure Payments</small><h2>Pay Safe.<br/><span>Pay Smart.</span></h2><p>Your money stays protected until both sides are satisfied.</p></div><Logo small/></div><div className="quick-grid"><button onClick={()=>go("send")}><PaperPlaneTilt/>Send</button><button onClick={()=>go("receive")}><QrCode/>Receive</button><button onClick={()=>go("transactions")}><Receipt/>History</button><button onClick={()=>go("settings")}><DotsThree/>More</button></div><div className="section-title"><h3>Active Transaction</h3><button onClick={()=>go("transactions")}>See all</button></div><button className="tx-card" onClick={()=>{setSelectedTx(sampleTx[0]);go("transaction-details")}}><div className="tx-icon"><Package/></div><div><b>#{sampleTx[0].id}</b><span>{sampleTx[0].item}</span></div><div className="right"><em>In Escrow</em><strong>{money(sampleTx[0].amount)}</strong></div></button><div className="progress"><span className="done">Paid</span><span className="done">In Escrow</span><span>Delivery</span><span>Complete</span></div></Shell>,
  send:<Shell screen={screen} setScreen={setScreen} title="Send Payment"><div className="stepper"><b>1</b><i/><span>2</span><i/><span>3</span></div><label>Recipient<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Name or phone number"/></label><label>Amount<div className="amount-input"><span>GH₵</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div></label><label>Purpose<select><option>Electronics purchase</option><option>Service payment</option><option>Marketplace order</option></select></label><label>Release payment when<select><option>I confirm item is received</option><option>Both parties confirm</option></select></label><div className="safe-note"><ShieldCheck/>Protected by ProofPay escrow</div><button className="primary full" onClick={()=>go("review")}>Continue</button></Shell>,
  receive:<Shell screen={screen} setScreen={setScreen} title="Receive Payment"><div className="segmented"><button className="active">QR Code</button><button>My Details</button></div><div className="qr"><QrCode weight="duotone"/><Logo small/></div><h2 className="center">Share your ProofPay ID</h2><p className="center muted">Let others pay you securely.</p><div className="copy-row"><b>+233 24 123 4567</b><button onClick={()=>navigator.clipboard?.writeText("+233241234567")}><Copy/></button></div><button className="primary full"><ShareNetwork/> Share</button><div className="safe-note"><ShieldCheck/>Receive money securely with escrow protection.</div></Shell>,
  review:<Shell screen={screen} setScreen={setScreen} title="Review Transaction"><div className="product"><div className="product-art">💻</div><div><b>MacBook Air (Used)</b><span>Electronics · Used</span></div><strong>{money(amount)}</strong></div><div className="people"><div><span>Buyer</span><b>You</b></div><div><span>Seller</span><b>{recipient}</b></div></div><div className="summary"><p><span>Amount</span><b>{money(amount)}</b></p><p><span>Escrow fee (1%)</span><b>{money(amount*.01)}</b></p><hr/><p><strong>Total</strong><strong>{money(amount*1.01)}</strong></p></div><div className="safe-note"><ShieldCheck/>Held securely until you confirm delivery.</div><button className="primary full" onClick={()=>go("momo")}>Confirm Transaction</button></Shell>,
  momo:<Shell screen={screen} setScreen={setScreen} title="MoMo Authorization"><div className="wallet-row momo"><div className="mtn">MTN</div><div><b>MTN MoMo</b><span>+233 24 123 4567</span></div><CaretRight/></div><div className="summary"><p><span>Amount</span><b>{money(amount)}</b></p><p><span>Escrow fee</span><b>{money(amount*.01)}</b></p><hr/><p><strong>Total to pay</strong><strong>{money(amount*1.01)}</strong></p></div><h3>Enter MoMo OTP</h3><p className="muted">A 6-digit code has been sent to your phone.</p><div className="otp">{[1,4,7,2,9,0].map((n,i)=><input key={i} value={n} readOnly/>)}</div><button className="primary full" onClick={()=>go("success")}>Authorize Payment</button></Shell>,
  success:<Shell screen={screen} setScreen={setScreen} title=""><div className="success-icon"><ShieldCheck weight="fill"/></div><h1 className="center">Payment Successful!</h1><p className="center muted">Your payment is now secured in escrow.</p><div className="summary"><p><span>Transaction ID</span><b>#PP482910</b></p><p><span>Amount</span><b>{money(amount)}</b></p><p><span>Payment method</span><b>MTN MoMo</b></p></div><div className="safe-note"><Lock/>We’ll notify you when delivery is ready for release.</div><button className="primary full" onClick={()=>go("transaction-details")}>View Transaction</button><button className="secondary full" onClick={()=>go("home")}>Go Home</button></Shell>,
  transactions:<Shell screen={screen} setScreen={setScreen} title="Transactions"><div className="search"><MagnifyingGlass/><input placeholder="Search transactions"/><SlidersHorizontal/></div><div className="chips"><button className="active">All</button><button>In Escrow</button><button>Completed</button><button>Disputed</button></div><div className="tx-list">{sampleTx.map(t=><button key={t.id} className="tx-card" onClick={()=>{setSelectedTx(t);go("transaction-details")}}><div className="tx-icon"><Package/></div><div><b>{t.item}</b><span>#{t.id} · {t.date}</span></div><div className="right"><strong>{money(t.amount)}</strong><em className={t.status.toLowerCase().replace(" ","-")}>{t.status}</em></div></button>)}</div></Shell>,
  "transaction-details":<Shell screen={screen} setScreen={setScreen} title="Transaction Details"><div className="product"><div className="product-art">📦</div><div><b>{selectedTx.item}</b><span>#{selectedTx.id}</span></div><strong>{money(selectedTx.amount)}</strong></div><div className="people"><div><span>Buyer</span><b>You</b></div><div><span>Seller</span><b>{selectedTx.party}</b></div></div><h3>Transaction Progress</h3><div className="progress large"><span className="done">Paid</span><span className="done">In Escrow</span><span>Delivery</span><span>Complete</span></div><div className="summary"><p><span>Item price</span><b>{money(selectedTx.amount)}</b></p><p><span>Protection fee (2%)</span><b>{money(selectedTx.amount*.02)}</b></p><hr/><p><strong>Total</strong><strong>{money(selectedTx.amount*1.02)}</strong></p></div><div className="two-buttons"><button className="secondary"><ChatCircleDots/> Message</button><button className="danger" onClick={()=>go("dispute")}><WarningCircle/> Dispute</button></div><button className="primary full" onClick={()=>go("release")}>Release Payment</button></Shell>,
  release:<Shell screen={screen} setScreen={setScreen} title="Release Payment"><div className="delivery"><CheckCircle weight="fill"/><h2>Delivery Verified</h2><p>Confirm the item has arrived as expected.</p></div><div className="summary"><p><span>{selectedTx.item}</span><b>{money(selectedTx.amount)}</b></p><p><span>Protection fee</span><b>{money(selectedTx.amount*.02)}</b></p><hr/><p><strong>Total to release</strong><strong>{money(selectedTx.amount)}</strong></p></div><div className="safe-note"><ShieldCheck/>Funds will be released to the seller.</div><button className="primary full" onClick={()=>{alert("Demo: funds released successfully");go("transactions")}}>Release Funds</button></Shell>,
  dispute:<Shell screen={screen} setScreen={setScreen} title="File a Dispute"><div className="issue-grid">{[[Package,"Item not received"],[Package,"Item not as described"],[Wallet,"Unauthorized payment"],[ArrowLeft,"Refund issue"],[WarningCircle,"Damaged item"],[DotsThree,"Other issue"]].map(([I,t],i)=><button className={i===0?"selected":""} key={t}><I/>{t}</button>)}</div><label>Add a short description<textarea placeholder="Tell us what happened..."/></label><h3>Add evidence</h3><div className="evidence"><button><Camera/>Photo</button><button><FileText/>Document</button><button><LinkSimple/>Link</button></div><button className="primary full" onClick={()=>{alert("Dispute submitted for review");go("messages")}}>Submit Dispute</button></Shell>,
  messages:<Shell screen={screen} setScreen={setScreen} title="Messages"><div className="search"><MagnifyingGlass/><input placeholder="Search messages"/></div><div className="message-list">{[["ProofPay Support","We’ve received your dispute.",2],["Jane (Support)","Here’s an update on your case.",1],["Dispute #PP482910","We need a bit more information.",1],["Account & Security","Tips to keep your account safe.",0],["Payments Team","Your refund has been processed.",0]].map(([n,m,c])=><button key={n}><div className="msg-avatar"><ChatCircleDots/></div><div><b>{n}</b><span>{m}</span></div>{c>0&&<i>{c}</i>}</button>)}</div></Shell>,
  support:<Shell screen={screen} setScreen={setScreen} title="Agents & Support"><div className="support-grid"><button><ChatCircleDots/><b>Live Chat</b><span>Chat with our team</span></button><button><BookOpen/><b>Help Center</b><span>Find answers</span></button><button><Phone/><b>Call Support</b><span>Speak to an agent</span></button><button><UsersThree/><b>Find an Agent</b><span>In your area</span></button></div><div className="escalate"><ShieldCheck/><div><small>NEED MORE HELP?</small><b>Escalate Your Case</b></div><CaretRight/></div><div className="hours"><b>Support hours</b><span>Mon – Sun, 8:00 AM – 8:00 PM</span></div></Shell>,
  notifications:<Shell screen={screen} setScreen={setScreen} title="Notifications"><div className="chips"><button className="active">All</button><button>Payments</button><button>Security</button><button>Support</button></div><div className="notification-list">{[[CheckCircle,"Payment released","Your payment of GH₵8,000 was released."],[Fingerprint,"In review","Your identity verification is under review."],[Receipt,"Payment received","You received GH₵5,000 from John D."],[Headset,"Support update","Your support ticket has been updated."],[Bell,"New feature","You can now pay with mobile money across Africa."]].map(([I,t,s],i)=><div key={t}><I/><div><b>{t}</b><span>{s}</span></div><small>{i+1}h ago</small></div>)}</div></Shell>,
  profile:<Shell screen={screen} setScreen={setScreen} title="Profile"><div className="profile-card"><div className="big-avatar">EA</div><div><h2>{user.name||"Emmanuella Adu-Boahene"}</h2><span>{user.email||"emmanuella@example.com"}</span><em><CheckCircle/> Verified</em></div></div><div className="stats"><div><b>GH₵124,500</b><span>Total Volume</span></div><div><b>12</b><span>Successful Trades</span></div></div><div className="menu">{[[UserCircle,"Personal Information"],[ShieldCheck,"Verification & Security","kyc"],[Wallet,"Payment Methods","wallets"],[GearSix,"Preferences","settings"],[Headset,"Help & Support","support"]].map(([I,t,s])=><button key={t} onClick={()=>s&&go(s)}><I/><span>{t}</span><CaretRight/></button>)}</div><button className="logout" onClick={()=>{localStorage.removeItem("proofpay_demo_user");setAuthed(false)}}><SignOut/>Log Out</button></Shell>,
  kyc:<Shell screen={screen} setScreen={setScreen} title="Verification"><div className="verify-hero"><Fingerprint/><h2>Verify your identity</h2><p>Trade safely and unlock higher limits.</p></div><div className="kyc-list">{[[IdentificationCard,"Personal Information","Completed"],[FileText,"ID Verification","Completed"],[UserCircle,"Selfie Check","In review"],[MapPin,"Address Proof","Not started"]].map(([I,t,s],i)=><div key={t}><span className="num">{i+1}</span><I/><div><b>{t}</b><span>{i<2?"Verified information":"Complete this step"}</span></div><em className={s==="Completed"?"ok":s==="In review"?"review":""}>{s}</em></div>)}</div><button className="primary full">Continue Verification</button></Shell>,
  settings:<Shell screen={screen} setScreen={setScreen} title="Settings"><div className="menu grouped"><h3>Security</h3>{[[Fingerprint,"Biometric Login"],[ShieldCheck,"Two-Factor Authentication"],[Key,"Change PIN"],[DeviceMobile,"Manage Devices"]].map(([I,t],i)=><button key={t}><I/><span>{t}</span>{i<2?<span className="toggle on"/>:<CaretRight/>}</button>)}<h3>Notifications</h3>{[[Bell,"Transaction Alerts"],[Bell,"Promotions & Updates"]].map(([I,t])=><button key={t}><I/><span>{t}</span><span className="toggle on"/></button>)}<h3>More</h3><button onClick={()=>go("support")}><Headset/><span>Help & Support</span><CaretRight/></button><button><FileText/><span>Terms & Privacy</span><CaretRight/></button></div></Shell>,
  wallets:<Shell screen={screen} setScreen={setScreen} title="Wallet & Payment Methods"><h3>Mobile Money</h3>{[["MTN","MTN MoMo","+233 24 123 4567"],["t","Telecel Cash","+233 20 987 6543"],["A","AT Money","+233 55 112 3344"]].map(([logo,n,p],i)=><div className="wallet-row" key={n}><div className={`wallet-logo w${i}`}>{logo}</div><div><b>{n}</b><span>{p}</span></div><em>Active</em><CaretRight/></div>)}<h3>Bank Account</h3><div className="wallet-row"><div className="wallet-logo bank"><Bank/></div><div><b>Stanbic Bank Ghana</b><span>•••• 5678</span></div><em>Verified</em><CaretRight/></div><button className="add-method"><Plus/> Link another payment method</button></Shell>,
  ussd:<Shell screen={screen} setScreen={setScreen} title="USSD Access"><div className="ussd-hero"><DeviceMobile/><div><small>Dial</small><h1>*719#</h1><span>to access ProofPay</span></div></div><h3>USSD Menu Preview</h3><pre>Welcome to ProofPay{`\n`}1. Make Payment{`\n`}2. Approve Release{`\n`}3. Check Status{`\n`}4. My Account{`\n`}5. Help</pre><h3>Quick Actions</h3><div className="quick-actions"><button><PaperPlaneTilt/>Create Payment</button><button><CheckCircle/>Approve Release</button><button><MagnifyingGlass/>Check Status</button><button><Headset/>Get Help</button></div></Shell>
 };
 return views[screen] || views.home;
}
